# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aee43df496af1da54ed27f3600e4c88c83d70140f60e3812ecc8a2b098fac010e8ed2ce523f47606c55c44e4d87748624f17ef9e0c5cf7d68976828e31f960d

test:
  secret_key_base: ad313a7616c397a64641bff3e3eaa5fac69341c643f9b18ba328d96b6ce0b984907c0bb00171607edd2ac8252216b026a49bba311cd7d5d0cb5458695f25bcee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
